### ISSUE TITLE
Can't start on linux

### ISSUE THREAD

**Issue by vlaaad** [oakes/Paravim#1]
Exception I get:
```clj
{:clojure.main/message
 "Execution error (UnsatisfiedLinkError) at org.lwjgl.system.linux.LinuxLibrary/loadLibrary (LinuxLibrary.java:32).\nFailed to dynamically load library: /tmp/lwjglvlaaad/3.2.3-build-13/libvim.so(error = null)\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.UnsatisfiedLinkError,
  :clojure.error/line 32,
  :clojure.error/cause
  "Failed to dynamically load library: /tmp/lwjglvlaaad/3.2.3-build-13/libvim.so(error = null)",
  :clojure.error/symbol
  org.lwjgl.system.linux.LinuxLibrary/loadLibrary,
  :clojure.error/source "LinuxLibrary.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type java.lang.UnsatisfiedLinkError,
    :message
    "Failed to dynamically load library: /tmp/lwjglvlaaad/3.2.3-build-13/libvim.so(error = null)",
    :at
    [org.lwjgl.system.linux.LinuxLibrary
     loadLibrary
     "LinuxLibrary.java"
     32]}],
  :trace
  [[org.lwjgl.system.linux.LinuxLibrary
    loadLibrary
    "LinuxLibrary.java"
    32]
   [org.lwjgl.system.linux.LinuxLibrary <init> "LinuxLibrary.java" 19]
   [org.lwjgl.system.APIUtil apiCreateLibrary "APIUtil.java" 123]
   [org.lwjgl.system.Library loadNative "Library.java" 360]
   [org.lwjgl.system.Library
    loadNativeFromLibraryPath
    "Library.java"
    349]
   [org.lwjgl.system.Library loadNative "Library.java" 264]
   [org.lwjgl.system.Library loadNative "Library.java" 222]
   [org.lwjgl.system.Library loadNative "Library.java" 203]
   [org.lwjgl.system.Library loadNative "Library.java" 185]
   [libvim_clj.core$__GT_vim$fn__7486 invoke "core.clj" 48]
   [libvim_clj.core$__GT_vim invokeStatic "core.clj" 47]
   [libvim_clj.core$__GT_vim invoke "core.clj" 37]
   [paravim.vim$__GT_vim invokeStatic "vim.clj" 253]
   [paravim.vim$__GT_vim invoke "vim.clj" 252]
   [paravim.start$init invokeStatic "start.clj" 181]
   [paravim.start$init invoke "start.clj" 179]
   [paravim.start$start invokeStatic "start.clj" 205]
   [paravim.start$start invoke "start.clj" 203]
   [paravim.start$_main invokeStatic "start.clj" 224]
   [paravim.start$_main doInvoke "start.clj" 222]
   [clojure.lang.RestFn invoke "RestFn.java" 397]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.RestFn applyTo "RestFn.java" 132]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.core$apply invokeStatic "core.clj" 665]
   [clojure.main$main_opt invokeStatic "main.clj" 514]
   [clojure.main$main_opt invoke "main.clj" 510]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause
  "Failed to dynamically load library: /tmp/lwjglvlaaad/3.2.3-build-13/libvim.so(error = null)"}}
```

There is a file at a path `/tmp/lwjglvlaaad/3.2.3-build-13/libvim.so`, marking it executable does not help.

**Comment by oakes** [comment]
Is your system 64 bit? And what distro?

**Comment by vlaaad** [comment]
ubuntu 19.04, 64 bit

**Comment by oakes** [comment]
K. I'm on ubuntu 18.04 with openjdk 11. I just tried a fresh install via a live usb and installed everything from scratch and it worked for me. I wonder if there is something about the latest version of ubuntu that is causing it. Either that or i messed up how i built the binary. [This is the commit](https://github.com/oakes/libvim/commit/f3990ad4e343f74cd6c1355d1e641ccbe732f70b) i made that enabled building libvim as a shared library. I remembered to enable `-fPIC` at least.

**Comment by vlaaad** [comment]
Tried on another linux machine with ubuntu 19.04, same error. `java -version` says:
```
vlaaad@stoldt1220 ~> java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by oakes** [comment]
I managed to reproduce this on a different computer with an intel processor. The one i compiled libvim on had an amd. I'll try recompiling it on the intel computer and see what happens.

**Comment by oakes** [comment]
OK i *think* i figured it out. It wasn't amd vs intel, it was that i wasn't linking to ncurses so i made [this fix](https://github.com/oakes/libvim/commit/ceee0a01a7f8fa2bddfaf8a8d2b3652d4bade7e1). Can you try the latest master? You should be able to do it with this command:

```
clj -Sdeps "{:deps {paravim {:git/url \""https://github.com/oakes/Paravim\"" :sha \""41c2f23eca145193a23e3367194e0a63ebb623c7\""}}}" -m paravim.start
```

**Comment by vlaaad** [comment]
That solved reported issue, although I still can't start it:
```
vlaaad@stoldt1220 ~> clj -Sdeps "{:deps {paravim {:git/url \""https://github.com/oakes/Paravim\"" :sha \""41c2f23eca145193a23e3367194e0a63ebb623c7\""}}}" -m paravim.start
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "main" Syntax error compiling at (text.clj:8:29).
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3707)
	at clojure.lang.Compiler$MapExpr.eval(Compiler.java:3054)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at paravim.core$eval144$loading__6706__auto____145.invoke(core.cljc:1)
	at paravim.core$eval144.invokeStatic(core.cljc:1)
	at paravim.core$eval144.invoke(core.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at paravim.start$eval138$loading__6706__auto____139.invoke(start.clj:1)
	at paravim.start$eval138.invokeStatic(start.clj:1)
	at paravim.start$eval138.invoke(start.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_stb.so
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.stb.LibSTB.<clinit>(LibSTB.java:17)
	at org.lwjgl.stb.STBTTFontinfo.<clinit>(STBTTFontinfo.java:29)
	at play_cljc.text$__GT_baked_font.invokeStatic(text.clj:39)
	at play_cljc.text$__GT_baked_font.invoke(text.clj:27)
	at play_cljc.text$__GT_baked_font.invokeStatic(text.clj:30)
	at play_cljc.text$__GT_baked_font.invoke(text.clj:27)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3702)
	... 87 more
```

**Comment by oakes** [comment]
Ah weird. I double checked the pom.xml and it definitely lists `lwjgl-stb` in the dependencies...

**Comment by vlaaad** [comment]
Tried running with suggested java properties set:
```
vlaaad@stoldt1220 ~> clj -J-Dorg.lwjgl.util.Debug=true -J-Dorg.lwjgl.util.DebugLoader=true -Sdeps "{:deps {paravim {:git/url \""https://github.com/oakes/Paravim\"" :sha \""41c2f23eca145193a23e3367194e0a63ebb623c7\""}}}" -m paravim.start
[LWJGL] Version: 3.2.3 build 13
[LWJGL] 	 OS: Linux v5.0.0-27-generic
[LWJGL] 	JRE: 11.0.1 amd64
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v11.0.1+13 by Oracle Corporation
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: /tmp/lwjglvlaaad/3.2.3-build-13/liblwjgl.so
[LWJGL] 	Loaded from org.lwjgl.librarypath: /tmp/lwjglvlaaad/3.2.3-build-13/liblwjgl.so
[LWJGL] Loading JNI library: lwjgl_stb
[LWJGL] 	Module: org.lwjgl.stb
[LWJGL] 	liblwjgl_stb.so not found in org.lwjgl.librarypath=/tmp/lwjglvlaaad/3.2.3-build-13
[LWJGL] 	linux/x64/org/lwjgl/stb/liblwjgl_stb.so not found in java.library.path=/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
[LWJGL] 	liblwjgl_stb.so not found in java.library.path
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
Exception in thread "main" Syntax error compiling at (text.clj:8:29).
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3707)
	at clojure.lang.Compiler$MapExpr.eval(Compiler.java:3054)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at paravim.core$eval144$loading__6706__auto____145.invoke(core.cljc:1)
	at paravim.core$eval144.invokeStatic(core.cljc:1)
	at paravim.core$eval144.invoke(core.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at paravim.start$eval138$loading__6706__auto____139.invoke(start.clj:1)
	at paravim.start$eval138.invokeStatic(start.clj:1)
	at paravim.start$eval138.invoke(start.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl_stb.so
	at org.lwjgl.system.Library.loadSystem(Library.java:162)
	at org.lwjgl.stb.LibSTB.<clinit>(LibSTB.java:17)
	at org.lwjgl.stb.STBTTFontinfo.<clinit>(STBTTFontinfo.java:29)
	at play_cljc.text$__GT_baked_font.invokeStatic(text.clj:39)
	at play_cljc.text$__GT_baked_font.invoke(text.clj:27)
	at play_cljc.text$__GT_baked_font.invokeStatic(text.clj:30)
	at play_cljc.text$__GT_baked_font.invoke(text.clj:27)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3702)
	... 87 more

```

**Comment by vlaaad** [comment]
Maybe in case of git dependency where there is actually no a jar it can't load it?

**Comment by oakes** [comment]
Ah that could be. Can you clone the Paravim repo and run `clj -A:dev:linux native` ?

**Comment by vlaaad** [comment]
it worked!

**Comment by oakes** [comment]
Sweet! I just pushed a snapshot. As a final test can you run this?

```
clj -Sdeps "{:deps {paravim {:mvn/version \""0.2.0-SNAPSHOT\""}}}" -m paravim.start
```

**Comment by vlaaad** [comment]
Works great, thank you!

**Comment by oakes** [comment]
Great, i pushed 0.2.0 with the fix, thanks for the help.
